#:schema node_modules/wrangler/config-schema.json
name = "creovate"
main = ".vercel/cache/wrangler_deploy/index.js"
compatibility_date = "2024-05-15"
compatibility_flags = ["nodejs_compat"]

# Bind a D1 database. D1 is Cloudflare's native serverless SQL database.
[[d1_databases]]
binding = "DB"
database_name = "creovate-db"
database_id = "your-database-id" # This will be replaced when you create the database

[build]
command = "npx @cloudflare/next-on-pages@1"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[env.preview.vars]
NODE_ENV = "development"

[env.production.vars]
NODE_ENV = "production"
