import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for YT Copilot - AI co-pilot for YouTubers.',
  robots: {
    index: true,
    follow: true,
  },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
          <div className="mb-8">
            <Link href="/" className="text-red-600 dark:text-red-400 hover:underline">
              ← Back to Home
            </Link>
          </div>
          
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-8">
            Terms of Service
          </h1>
          
          <div className="prose dark:prose-invert max-w-none">
            <p className="text-gray-600 dark:text-gray-400 mb-6">
              Last updated: {new Date().toLocaleDateString()}
            </p>
            
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using YT Copilot ("the Service"), you accept and agree to be bound by the terms and provision of this agreement.
            </p>
            
            <h2>2. Description of Service</h2>
            <p>
              YT Copilot is an AI co-pilot for YouTubers that helps optimize channels, analyze performance, and grow YouTube presence using advanced AI technology and proprietary algorithms.
            </p>
            
            <h2>3. User Accounts and YouTube Integration</h2>
            <p>
              To access the Service, you must register for an account and may connect your YouTube channel. You are responsible for maintaining the confidentiality of your account credentials and YouTube access tokens.
            </p>
            
            <h2>4. Acceptable Use</h2>
            <p>
              You agree to use the Service only for lawful purposes and in accordance with these Terms. You may not use the Service:
            </p>
            <ul>
              <li>To violate YouTube's Terms of Service or Community Guidelines</li>
              <li>To violate any applicable laws or regulations</li>
              <li>To transmit harmful, offensive, or inappropriate content</li>
              <li>To interfere with or disrupt the Service</li>
              <li>To attempt to gain unauthorized access to the Service or other users' data</li>
              <li>To abuse or circumvent our AI optimization features</li>
            </ul>
            
            <h2>5. YouTube Data and API Usage</h2>
            <p>
              YT Copilot uses YouTube API Services to provide optimization features. By using our Service, you agree to be bound by the YouTube Terms of Service. You can revoke YT Copilot's access to your data via Google security settings.
            </p>
            
            <h2>6. AI-Generated Content and Optimizations</h2>
            <p>
              Content optimizations and suggestions generated by our AI (powered by OpenAI and proprietary algorithms) are provided as-is. While we strive for accuracy, we cannot guarantee the accuracy, completeness, or effectiveness of AI-generated recommendations.
            </p>
            
            <h2>7. Data Storage and Security</h2>
            <p>
              Your data is stored securely using Turso database technology. We implement enterprise-grade security measures to protect your information, but you acknowledge that no system is 100% secure.
            </p>
            
            <h2>8. Proprietary Technology</h2>
            <p>
              YT Copilot contains proprietary algorithms and technology. You may not reverse engineer, decompile, or attempt to extract our proprietary methods and algorithms.
            </p>
            
            <h2>9. Subscription and Billing</h2>
            <p>
              Some features of the Service require a paid subscription. Billing terms are outlined in your subscription agreement. Fees are non-refundable except as required by law.
            </p>
            
            <h2>10. Termination</h2>
            <p>
              We may terminate or suspend your account and access to the Service at our sole discretion, without prior notice, for conduct that we believe violates these Terms or YouTube's policies.
            </p>
            
            <h2>11. Limitation of Liability</h2>
            <p>
              The Service is provided "as is" without warranties of any kind. We shall not be liable for any damages arising from your use of the Service, including but not limited to YouTube channel performance or monetization issues.
            </p>
            
            <h2>12. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of any material changes via email or through the Service.
            </p>
            
            <h2>13. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p>
              Email: legal@yt-copilot.strivio.world<br />
              Website: https://yt-copilot.strivio.world
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
