import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for Creovate - AI-powered content creation platform.',
  robots: {
    index: true,
    follow: true,
  },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
          <div className="mb-8">
            <Link href="/" className="text-blue-600 dark:text-blue-400 hover:underline">
              ← Back to Home
            </Link>
          </div>
          
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-8">
            Terms of Service
          </h1>
          
          <div className="prose dark:prose-invert max-w-none">
            <p className="text-gray-600 dark:text-gray-400 mb-6">
              Last updated: {new Date().toLocaleDateString()}
            </p>
            
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using Creovate ("the Service"), you accept and agree to be bound by the terms and provision of this agreement.
            </p>
            
            <h2>2. Description of Service</h2>
            <p>
              Creovate is an AI-powered content creation platform that helps users generate ideas, research trends, create content, and analyze performance.
            </p>
            
            <h2>3. User Accounts</h2>
            <p>
              To access certain features of the Service, you must register for an account. You are responsible for maintaining the confidentiality of your account credentials.
            </p>
            
            <h2>4. Acceptable Use</h2>
            <p>
              You agree to use the Service only for lawful purposes and in accordance with these Terms. You may not use the Service:
            </p>
            <ul>
              <li>To violate any applicable laws or regulations</li>
              <li>To transmit harmful, offensive, or inappropriate content</li>
              <li>To interfere with or disrupt the Service</li>
              <li>To attempt to gain unauthorized access to the Service</li>
            </ul>
            
            <h2>5. Content and Intellectual Property</h2>
            <p>
              You retain ownership of content you create using the Service. However, you grant us a license to use, store, and process your content to provide the Service.
            </p>
            
            <h2>6. AI-Generated Content</h2>
            <p>
              Content generated by our AI tools is provided as-is. While we strive for accuracy, we cannot guarantee the accuracy, completeness, or reliability of AI-generated content.
            </p>
            
            <h2>7. Privacy Policy</h2>
            <p>
              Your privacy is important to us. Please review our Privacy Policy, which also governs your use of the Service.
            </p>
            
            <h2>8. Subscription and Billing</h2>
            <p>
              Some features of the Service require a paid subscription. Billing terms are outlined in your subscription agreement.
            </p>
            
            <h2>9. Termination</h2>
            <p>
              We may terminate or suspend your account and access to the Service at our sole discretion, without prior notice, for conduct that we believe violates these Terms.
            </p>
            
            <h2>10. Limitation of Liability</h2>
            <p>
              The Service is provided "as is" without warranties of any kind. We shall not be liable for any damages arising from your use of the Service.
            </p>
            
            <h2>11. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of any material changes via email or through the Service.
            </p>
            
            <h2>12. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p>
              Email: legal@creovate.com<br />
              Address: [Your Company Address]
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
